// VS UniSystem mapper. CHR selection is latched through controller port $4016.
export class Mapper99 {
    constructor(cartridge, ram, prg, chr) {
        // Vs. Wrecking Crew is a DualSystem title. The commonly distributed
        // iNES image contains only the main-side CPU/PPU ROMs; the game waits
        // at $BF6E for an IRQ generated by the missing second cabinet side.
        // Treat that incomplete dump explicitly instead of silently showing a
        // permanent black screen.
        const isIncompleteDualSystemDump = prg.length === 0x8000 &&
            chr.length === 0x4000 &&
            prg[0x3F5A] === 0xAD && prg[0x3F5B] === 0x16 && prg[0x3F5C] === 0x40 &&
            prg[0x3F6D] === 0x58 && prg[0x3F6E] === 0x4C &&
            prg[0x3F6F] === 0x6E && prg[0x3F70] === 0xBF;
        if (isIncompleteDualSystemDump) {
            throw new Error('Vs. Wrecking Crew ROM 缺少 DualSystem 副机 ROM，请使用 NES 单机版 Wrecking Crew ROM');
        }
        this.cartridge = cartridge;
        this.ram = ram;
        this.prg = prg;
        this.chr = chr.length ? chr : new Uint8Array(0x2000);
        this.chrWritable = chr.length === 0;
        this.chrBank = 0;
    }
    read(address) {
        address &= 0xFFFF;
        if (address < 0x2000) return this.chr[(this.chrBank * 0x2000 + address) % this.chr.length];
        if (address >= 0x8000) return this.prg[(address - 0x8000) % this.prg.length];
        if (address >= 0x6000) return this.ram[address - 0x6000];
        return 0;
    }
    write(address, data) {
        address &= 0xFFFF;
        if (address < 0x2000) {
            if (this.chrWritable) this.chr[(this.chrBank * 0x2000 + address) % this.chr.length] = data;
        }
        else if (address === 0x4016) this.chrBank = (data >> 2) & 1;
        else if (address >= 0x6000 && address < 0x8000) this.ram[address - 0x6000] = data;
    }
    ppuClockHandle(scanLine, cycle) { }
}
